drop database inventory_management;
create database inventory_management;

\c inventory_management


CREATE TABLE WAREHOUSE(
W_ID SERIAL PRIMARY KEY ,
W_ZIP INTEGER , 
W_CAPACITY BIGINT 
);

CREATE TABLE CATEGORY(
C_ID SERIAL PRIMARY KEY ,
C_NAME VARCHAR(30) NOT NULL ,
C_PASTSALESAMT BIGINT ,
C_PASTSALESPRICE BIGINT
);

CREATE TABLE RETAILER(
RET_EMAIL VARCHAR(50) PRIMARY KEY ,
RET_NAME VARCHAR(50) ,
RET_PASSWD VARCHAR(100) ,
RET_ZIP INTEGER
);

CREATE TABLE SUPPLIER(
SUP_ID SERIAL PRIMARY KEY ,
SUP_RATING FLOAT ,
SUP_NAME VARCHAR(100) ,
SUP_CATEGORY INT ,
FOREIGN KEY(SUP_CATEGORY) REFERENCES CATEGORY(C_ID) ON DELETE CASCADE 
);

CREATE TABLE ITEMS(
I_ID SERIAL PRIMARY KEY ,
I_NAME VARCHAR(100) UNIQUE NOT NULL ,
I_PRICE FLOAT ,
I_QUANTITY INT ,
C_ID INT ,
FOREIGN KEY(C_ID) REFERENCES CATEGORY(C_ID) ON DELETE CASCADE 
);

CREATE TABLE W_MAP(
W_QUANTITY INT ,
W_ID INT ,
I_ID INT ,
FOREIGN KEY(W_ID) REFERENCES WAREHOUSE(W_ID) ON DELETE CASCADE ,
FOREIGN KEY(I_ID) REFERENCES ITEMS(I_ID) ON DELETE CASCADE
);

CREATE TABLE BUY(
BUY_ID SERIAL PRIMARY KEY ,
BUY_PRICE FLOAT ,
SUP_ID INT ,
FOREIGN KEY(SUP_ID) REFERENCES SUPPLIER(SUP_ID) ON DELETE CASCADE 
);

CREATE TABLE SELL(
SELL_ID SERIAL PRIMARY KEY ,
RET_EMAIL VARCHAR(50) ,
SELL_PRICE FLOAT ,
FOREIGN KEY(RET_EMAIL) REFERENCES RETAILER(RET_EMAIL) ON DELETE CASCADE 
);

CREATE TABLE BUY_MAP(
BUY_QUANTITY INT NOT NULL ,
BUY_ID INT ,
I_ID INT ,
FOREIGN KEY(I_ID) REFERENCES ITEMS(I_ID) ON DELETE CASCADE ,
FOREIGN KEY(BUY_ID) REFERENCES BUY(BUY_ID) ON DELETE CASCADE
);

CREATE TABLE SELL_MAP(
SELL_QUANTITY INT NOT NULL ,
SELL_ID INT ,
I_ID INT ,
FOREIGN KEY(I_ID) REFERENCES ITEMS(I_ID) ON DELETE CASCADE ,
FOREIGN KEY(SELL_ID) REFERENCES SELL(SELL_ID) ON DELETE CASCADE
);
